//Include any predeployment steps here, such as signing up for a Marketplace AMI or making any changes to a partner account. If there are no predeployment steps, leave this file empty.

== Predeployment steps

=== Generate AWS Systems Manager parameters

The Quick Start now uses AWS Systems Manager Parameter Store to hold the configuration and secrets for Darktrace vSensor. This is due to EC2 instance user data being https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html[unencrypted^].

https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-su-create.html[Create^] separate "Secure String" SSM Parameters in the expected AWS region for each of the following:

. vSensor Update Key (e.g. `abcdefg:12345678`)
. Darktrace Instance Hostname (e.g. `https://instancename.cloud.darktrace.com:443`)
. Darktrace Instance Push Token (e.g. `vsensor-push-token:123456abcdefg`)
. Darktrace Instance Proxy (e.g. `http://proxyname.example.com:3128`, `http://username@password:proxyname.example.com:3128` or `none` to not use a proxy)
. osSensor HMAC (e.g. `ossensorhmac123456abcdefg` or `none` to disable osSensor support)

You will provide the parameter names to the CloudFormation template, for the vSensor to automatically decrypt these values on start up.

Using SSM parameters provides the benefit that configurations can be more easily cycled out using the Auto Scaling Group Instance Refresh features, without having to redeploy the Quick Start template.

NOTE: Please review https://docs.aws.amazon.com/autoscaling/ec2/userguide/asg-instance-refresh.html[ASG Instance Refresh Documentation]. Refreshing all instances will cause an outage, since instances are terminated before new instances are created.

=== Register a push token

Register a new push token to enable connection between vSensor probes and an existing Darktrace on-premise or cloud instance. All of the vSensor instances in this deployment share the same push token.

. Log into the Darktrace console.
. On the main menu, choose *Admin > System Config*.
. In the *Push Probe Tokens* section, enter a label for the vSensor deployment.
. Choose *Add*. A token is generated in the form of `[label:string]`. 
. Record the token, as it only displays once. You must enter the token in the *Darktrace Instance push token* link:#_parameter_reference[parameter] field during Quick Start deployment.

If your Darktrace Instance is behind a firewall, you must grant access to the instance from the IP addresses of your NAT Gateways after deployment. For more information, see link:#post-deployment-steps[Post deployment steps], later in this guide.

NOTE: Darktrace cloud instances are already configured to allow push token access, no firewall changes are necessary.

=== Traffic Mirror Configuration Modes

It is important you must understand the different traffic mirroring options available before deploying.

A new option `CrossZoneLBEnable` has been provided to reduce bandwidth costs for traffic ingestion.

*If "No" is set* (the default), the load balancer will only send mirrored traffic to vSensors in the same Availability Zone as the mirror source. The same is true for osSensor traffic.

This option reduces costs by preventing mirror traffic from crossing zones, which can be substantial in large bandwidth environments.

WARNING: You must configure the number of vSensors deployed (minimum and desired) to meet or exceed the count of availability zones deployed to, otherwise traffic mirror sessions and osSensors in zones without vSensors will not be mirrored.

*If "Yes" is set*, it is possible to reduce the vSensor count as low as 1 without loss of traffic mirroring, this may be suited to small traffic environments.

NOTE: Select at least 2 availability zones for highly available fault tolerance.

